services:
  - type: web
    name: codecast-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JDoodle_clientId
        sync: false
      - key: JDoodle_clientSecret
        sync: false
